In [1]:
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

WARNING:tensorflow:From c:\MAIN\codenotes\AIML\project1\Customer-churn-prediction-ANN\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
#LOAD MODEL FOR PREDICTION

model=load_model('model.h5')

with open('encoder.pkl','rb') as file:
    oheencodergeo=pickle.load(file)
    
with open('encodegender.pkl','rb') as file:
    labelencodergender=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:tensorflow:From c:\MAIN\codenotes\AIML\project1\Customer-churn-prediction-ANN\venv\lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [3]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [4]:
#encoding Geography

encoded_geo=oheencodergeo.transform([[input_data['Geography']]]).toarray()
encoded_geo_df=pd.DataFrame(encoded_geo,columns=oheencodergeo.get_feature_names_out(['Geography']))
encoded_geo_df

c:\MAIN\codenotes\AIML\project1\Customer-churn-prediction-ANN\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [5]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [6]:
#combine with input data

input_df=pd.concat([input_df.drop("Geography",axis=1),encoded_geo_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [7]:
##labeltransform

input_df['Gender']=labelencodergender.transform(input_df['Gender'])
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [8]:
##scalling the data

scaled_input=scaler.transform(input_df)
scaled_input

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [9]:
##Prediction

prediction=model.predict(scaled_input)

prediction

1/1 [==============================] - 0s 127ms/step

array([[0.053781]], dtype=float32)

In [10]:
if(prediction[0][0]>0.5):
    print("Customer will exit.")
    
else:
    print("Customer will stay.")

Customer will stay.